#!/bin/bash

	#initialisation

if ! [[ -n "$1" ]];
then echo "Invalid command"
exit 1
fi
if ! [[ -n "$2" ]];
then echo "Empty cfiles"
exit 1
fi
if ! [[ -f $2 ]];
then echo "Cfile is missing"
exit 1
fi
test_name=$1
comp_arg="$(pwd)/$2"

	#generation


if [ -d $test_name ]
then rm -r $test_name
fi
mkdir $test_name
cd $test_name
echo -e "Test name: $test_name\n" >> tresult.txt

gcc -S -O0 -o prog0m32.txt -m32 $comp_arg -lm 2>>tresult.txt
if ! [[ -f prog0m32.txt ]]
then echo -e "Compilation error\n" >>tresult.txt
exit 1
fi
gcc -S -Ofast -o progfastm32.txt -m32 $comp_arg -lm 2>>tresult.txt
gcc -S -O0 -o prog0.txt $comp_arg -lm 2>>tresult.txt
gcc -S -Ofast -o progfast.txt $comp_arg -lm 2>>tresult.txt
gcc -S -Ofast -o progmn.txt -march=native $comp_arg -lm 2>>tresult.txt

echo -e "\nCompilation complete" >> tresult.txt

exit 0
